### ISSUE TITLE
Error: Cannot read property 'timeType' of undefined

### ISSUE THREAD

**Issue by MrLight** [rdmtc/node-red-contrib-sun-position#152]
**Describe the bug**
After Update to 1.1.0 the blind-control nodes gave the error "Cannot read property 'timeType' of undefined". I haven't found a solution yet to overcome.

A newly created blind-control node doesn't give the error. I suppose that a property which was introduced in 1.1.0 is not created, after the update.

**Comment by Hypnos3** [comment]
I Have released a version 1.1.1.
Can you please test if this will fix the Error? if not, can you please export the node with the error, so I can make more testing?

**Comment by MrLight** [comment]
Hi,
I have updated to 1.1.1 but the error remains.
I can force the error when I activate the auto trigger.

Here is the log output:
```
25 May 08:11:23 - [info] [blind-control:1375ef07.63f5d1] TypeError: Cannot read property 'timeType' of undefined
    at getRuleTimeData (/data/node_modules/node-red-contrib-sun-position/nodes/blind-control.js:687:24)
    at checkRuleForAT (/data/node_modules/node-red-contrib-sun-position/nodes/blind-control.js:934:25)
    at checkRules (/data/node_modules/node-red-contrib-sun-position/nodes/blind-control.js:1019:17)
    at sunBlindControlNode._inputCallback (/data/node_modules/node-red-contrib-sun-position/nodes/blind-control.js:1260:38)
    at sunBlindControlNode.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:199:18)
    at Immediate._onImmediate (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
25 May 08:11:23 - [error] [blind-control:1375ef07.63f5d1] Error: Cannot read property 'timeType' of undefined
```

The Node Export is like the following:
```
[{
	"id": "b094b010.d756",
	"type": "blind-control",
	"z": "897489dd.4d9368",
	"name": "",
	"topic": "",
	"positionConfig": "ca947504.e54f88",
	"outputs": "1",
	"autoTrigger": true,
	"autoTriggerTime": "60000",
	"startDelayTime": 10000,
	"storeName": "",
	"blindIncrement": "1",
	"blindOpenPos": "0",
	"blindClosedPos": "100",
	"blindPosReverse": false,
	"blindPosDefault": "open (max)",
	"blindPosDefaultType": "levelFixed",
	"overwriteExpire": "",
	"rules": [],
	"sunControlMode": "2",
	"sunFloorLength": "10",
	"sunMinAltitude": "10",
	"sunMinDelta": "",
	"blindPosMin": "closed (min)",
	"blindPosMinType": "levelFixed",
	"blindPosMax": "open (max)",
	"blindPosMaxType": "levelFixed",
	"smoothTime": "",
	"sunTopic": "",
	"windowTop": "200",
	"windowBottom": "10",
	"windowAzimuthStart": "222",
	"windowAzimuthEnd": "335",
	"oversteerValue": "",
	"oversteerValueType": "none",
	"oversteerCompare": "gte",
	"oversteerThreshold": "",
	"oversteerThresholdType": "num",
	"oversteerBlindPos": "open (max)",
	"oversteerBlindPosType": "levelFixed",
	"oversteer2Value": "",
	"oversteer2ValueType": "none",
	"oversteer2Compare": "gte",
	"oversteer2Threshold": "",
	"oversteer2ThresholdType": "num",
	"oversteer2BlindPos": "open (max)",
	"oversteer2BlindPosType": "levelFixed",
	"oversteer3Value": "",
	"oversteer3ValueType": "none",
	"oversteer3Compare": "gte",
	"oversteer3Threshold": "",
	"oversteer3ThresholdType": "num",
	"oversteer3BlindPos": "open (max)",
	"oversteer3BlindPosType": "levelFixed",
	"oversteerTopic": "",
	"x": 460,
	"y": 1774,
	"wires": [
		[]
	]
}, {
	"id": "ca947504.e54f88",
	"type": "position-config",
	"z": "",
	"name": "",
	"isValide": "true",
	"longitude": "0",
	"latitude": "0",
	"angleType": "deg",
	"timeZoneOffset": "99",
	"timeZoneDST": "0",
	"stateTimeFormat": "3",
	"stateDateFormat": "12"
}]
```

**Comment by Hypnos3** [comment]
Thank you, I have fixed this with Release 1.1.2.
