### ISSUE TITLE
Oversteer does not work when restricted to mode 2 (summer)

### ISSUE THREAD

**Issue by nikipore** [rdmtc/node-red-contrib-sun-position#431]
**Describe the bug**
The oversteer mode does not work when restricted to mode 2 (summer).

To reproduce, create a flow with a blind control node, set it to mode 2 (summer), create an oversteer rule which evaluates to true, and
1. don't restrict the rule to any mode,
2. restrict the rule to mode 2 (summer).

Inject a timestamp s.t. it is in default (sun control mode). In case 1, one sees in the node status that the oversteer rule is activated. In case 2, the oversteer rule is not activated.

**Screenshots**
N/A

**Expected behavior**
Case 1 is expected behavior, case 2 isn't.

**System information (please complete the following information):**
 - node-red-contrib-sun-position 2.2.0-beta2
 - Node-Red Version 2.2.2

**Additional context**
A test flow reduced to the very essence. I use the `flow.shadow` variable to indicate whether the sun is behind a house, say, in the west (`"W"`).
```json
[
    {
        "id": "16787abdb20404ee",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "dc6f132e12264e56",
        "type": "inject",
        "z": "16787abdb20404ee",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "W",
        "payloadType": "str",
        "x": 210,
        "y": 100,
        "wires": [
            [
                "5c9d036eb47e31f2"
            ]
        ]
    },
    {
        "id": "2b08a4d7ba5db4af",
        "type": "inject",
        "z": "16787abdb20404ee",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "str",
        "x": 210,
        "y": 140,
        "wires": [
            [
                "5c9d036eb47e31f2"
            ]
        ]
    },
    {
        "id": "5c9d036eb47e31f2",
        "type": "change",
        "z": "16787abdb20404ee",
        "name": "",
        "rules": [
            {
                "t": "set",
                "p": "#:(store)::shadow",
                "pt": "flow",
                "to": "payload",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 410,
        "y": 120,
        "wires": [
            []
        ]
    },
    {
        "id": "c0fdf4fca6318b09",
        "type": "blind-control",
        "z": "16787abdb20404ee",
        "name": "Case 1",
        "topic": "",
        "addIdType": "none",
        "addId": "",
        "positionConfig": "a962ddc.fbff22",
        "autoTrigger": false,
        "autoTriggerTime": "1200000",
        "startDelayTime": "10000",
        "contextStore": "store",
        "results": [
            {
                "p": "",
                "pt": "msgTopic",
                "v": "",
                "vt": "topic"
            },
            {
                "p": "",
                "pt": "msgPayload",
                "v": "",
                "vt": "level"
            },
            {
                "p": "slat",
                "pt": "msg",
                "v": "",
                "vt": "slat"
            },
            {
                "p": "blindCtrl",
                "pt": "msg",
                "v": "",
                "vt": "ctrlObj"
            }
        ],
        "blindIncrement": "0.05",
        "blindOpenPos": "1",
        "blindClosedPos": 0,
        "blindPosDefault": "open (max)",
        "blindPosDefaultType": "levelFixed",
        "slatPosDefault": "",
        "slatPosDefaultType": "none",
        "overwriteExpire": "",
        "rules": [],
        "sunControlMode": 16,
        "sunFloorLengthType": "num",
        "sunFloorLength": "",
        "sunMinDelta": "",
        "blindPosMin": "25%",
        "blindPosMinType": "levelFixed",
        "blindPosMax": "open (max)",
        "blindPosMaxType": "levelFixed",
        "blindOpenPosOffset": "",
        "blindClosedPosOffset": "",
        "sunSlat": "",
        "sunSlatType": "none",
        "smoothTime": "",
        "sunTopic": "",
        "windowTopType": "num",
        "windowTop": "",
        "windowBottomType": "num",
        "windowBottom": "",
        "windowAzimuthStartType": "numAzimuth",
        "windowAzimuthStart": "0",
        "windowAzimuthEndType": "numAzimuth",
        "windowAzimuthEnd": "359.9",
        "oversteers": [
            {
                "mode": 0,
                "valueType": "flow",
                "value": "#:(store)::shadow",
                "operator": "equal",
                "operatorText": "=",
                "thresholdType": "str",
                "threshold": "W",
                "onlySunInWindow": false,
                "blindPos": {
                    "type": "levelFixed",
                    "value": "open (max)"
                },
                "slatPos": {
                    "type": "none",
                    "value": ""
                }
            }
        ],
        "oversteerTopic": "",
        "x": 620,
        "y": 240,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "b66f3a99cf03f739",
        "type": "inject",
        "z": "16787abdb20404ee",
        "name": "",
        "props": [
            {
                "p": "parts",
                "v": "43200000",
                "vt": "str"
            }
        ],
        "repeat": "1",
        "crontab": "",
        "once": true,
        "onceDelay": 0.1,
        "topic": "",
        "x": 370,
        "y": 280,
        "wires": [
            [
                "c0fdf4fca6318b09",
                "37a58b5e5c46f4a7"
            ]
        ]
    },
    {
        "id": "37a58b5e5c46f4a7",
        "type": "blind-control",
        "z": "16787abdb20404ee",
        "name": "Case 2",
        "topic": "",
        "addIdType": "none",
        "addId": "",
        "positionConfig": "a962ddc.fbff22",
        "autoTrigger": false,
        "autoTriggerTime": "1200000",
        "startDelayTime": "10000",
        "contextStore": "store",
        "results": [
            {
                "p": "",
                "pt": "msgTopic",
                "v": "",
                "vt": "topic"
            },
            {
                "p": "",
                "pt": "msgPayload",
                "v": "",
                "vt": "level"
            },
            {
                "p": "slat",
                "pt": "msg",
                "v": "",
                "vt": "slat"
            },
            {
                "p": "blindCtrl",
                "pt": "msg",
                "v": "",
                "vt": "ctrlObj"
            }
        ],
        "blindIncrement": "0.05",
        "blindOpenPos": "1",
        "blindClosedPos": 0,
        "blindPosDefault": "open (max)",
        "blindPosDefaultType": "levelFixed",
        "slatPosDefault": "",
        "slatPosDefaultType": "none",
        "overwriteExpire": "",
        "rules": [],
        "sunControlMode": 16,
        "sunFloorLengthType": "num",
        "sunFloorLength": "",
        "sunMinDelta": "",
        "blindPosMin": "25%",
        "blindPosMinType": "levelFixed",
        "blindPosMax": "open (max)",
        "blindPosMaxType": "levelFixed",
        "blindOpenPosOffset": "",
        "blindClosedPosOffset": "",
        "sunSlat": "",
        "sunSlatType": "none",
        "smoothTime": "",
        "sunTopic": "",
        "windowTopType": "num",
        "windowTop": "",
        "windowBottomType": "num",
        "windowBottom": "",
        "windowAzimuthStartType": "numAzimuth",
        "windowAzimuthStart": "0",
        "windowAzimuthEndType": "numAzimuth",
        "windowAzimuthEnd": "359.9",
        "oversteers": [
            {
                "mode": 1,
                "valueType": "flow",
                "value": "#:(store)::shadow",
                "operator": "equal",
                "operatorText": "=",
                "thresholdType": "str",
                "threshold": "W",
                "onlySunInWindow": false,
                "blindPos": {
                    "type": "levelFixed",
                    "value": "open (max)"
                },
                "slatPos": {
                    "type": "none",
                    "value": ""
                }
            }
        ],
        "oversteerTopic": "",
        "x": 620,
        "y": 320,
        "wires": [
            [],
            []
        ]
    }
]```

**Comment by Hypnos3** [comment]
The problem is fixed in the latest version. node-red-contrib-sun-position@2.2.0-beta3

Since this version has undergone some changes internally, I have this but still released as beta. That means you can't update it via Node-Red, but only via the command line.

**Comment by nikipore** [comment]
Bumped to node-red-contrib-sun-position@2.2.0-beta3. Bug still there in my test flow.

**Comment by Hypnos3** [comment]
Have you selected again the limitation and re-drployed?
![image](https://user-images.githubusercontent.com/12692680/159568657-c386cbda-10d7-498c-a57c-0c1c99a6e1cf.png)

Alternatively you have to change the "mode" from `1` to `16`
![image](https://user-images.githubusercontent.com/12692680/159568992-6ab9f667-8dae-4b53-a53b-e34e9378cf9e.png)

The mode `1` is maximize not sun control. The option for this select was broken in the html and to thus the wrong value is stored.

```
[
    {
        "id": "16787abdb20404ee",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "dc6f132e12264e56",
        "type": "inject",
        "z": "16787abdb20404ee",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "W",
        "payloadType": "str",
        "x": 210,
        "y": 100,
        "wires": [
            [
                "5c9d036eb47e31f2"
            ]
        ]
    },
    {
        "id": "2b08a4d7ba5db4af",
        "type": "inject",
        "z": "16787abdb20404ee",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "str",
        "x": 210,
        "y": 140,
        "wires": [
            [
                "5c9d036eb47e31f2"
            ]
        ]
    },
    {
        "id": "5c9d036eb47e31f2",
        "type": "change",
        "z": "16787abdb20404ee",
        "name": "",
        "rules": [
            {
                "t": "set",
                "p": "#:(store)::shadow",
                "pt": "flow",
                "to": "payload",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 410,
        "y": 120,
        "wires": [
            []
        ]
    },
    {
        "id": "c0fdf4fca6318b09",
        "type": "blind-control",
        "z": "16787abdb20404ee",
        "name": "Case 1",
        "topic": "",
        "addIdType": "none",
        "addId": "",
        "positionConfig": "a962ddc.fbff22",
        "autoTrigger": false,
        "autoTriggerTime": "1200000",
        "startDelayTime": "10000",
        "contextStore": "store",
        "results": [
            {
                "p": "",
                "pt": "msgTopic",
                "v": "",
                "vt": "topic"
            },
            {
                "p": "",
                "pt": "msgPayload",
                "v": "",
                "vt": "level"
            },
            {
                "p": "slat",
                "pt": "msg",
                "v": "",
                "vt": "slat"
            },
            {
                "p": "blindCtrl",
                "pt": "msg",
                "v": "",
                "vt": "ctrlObj"
            }
        ],
        "blindIncrement": "0.05",
        "blindOpenPos": "1",
        "blindClosedPos": 0,
        "blindPosDefault": "open (max)",
        "blindPosDefaultType": "levelFixed",
        "slatPosDefault": "",
        "slatPosDefaultType": "none",
        "overwriteExpire": "",
        "rules": [],
        "sunControlMode": 16,
        "sunFloorLengthType": "num",
        "sunFloorLength": "",
        "sunMinDelta": "",
        "blindPosMin": "25%",
        "blindPosMinType": "levelFixed",
        "blindPosMax": "open (max)",
        "blindPosMaxType": "levelFixed",
        "blindOpenPosOffset": "",
        "blindClosedPosOffset": "",
        "sunSlat": "",
        "sunSlatType": "none",
        "smoothTime": "",
        "sunTopic": "",
        "windowTopType": "num",
        "windowTop": "",
        "windowBottomType": "num",
        "windowBottom": "",
        "windowAzimuthStartType": "numAzimuth",
        "windowAzimuthStart": "0",
        "windowAzimuthEndType": "numAzimuth",
        "windowAzimuthEnd": "359.9",
        "oversteers": [
            {
                "mode": 0,
                "valueType": "flow",
                "value": "#:(store)::shadow",
                "operator": "equal",
                "operatorText": "=",
                "thresholdType": "str",
                "threshold": "W",
                "onlySunInWindow": false,
                "blindPos": {
                    "type": "levelFixed",
                    "value": "open (max)"
                },
                "slatPos": {
                    "type": "none",
                    "value": ""
                }
            }
        ],
        "oversteerTopic": "",
        "x": 620,
        "y": 240,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "b66f3a99cf03f739",
        "type": "inject",
        "z": "16787abdb20404ee",
        "name": "",
        "props": [
            {
                "p": "parts",
                "v": "43200000",
                "vt": "str"
            }
        ],
        "repeat": "1",
        "crontab": "",
        "once": true,
        "onceDelay": 0.1,
        "topic": "",
        "x": 370,
        "y": 280,
        "wires": [
            [
                "c0fdf4fca6318b09",
                "37a58b5e5c46f4a7"
            ]
        ]
    },
    {
        "id": "37a58b5e5c46f4a7",
        "type": "blind-control",
        "z": "16787abdb20404ee",
        "name": "Case 2",
        "topic": "",
        "addIdType": "none",
        "addId": "",
        "positionConfig": "a962ddc.fbff22",
        "autoTrigger": false,
        "autoTriggerTime": "1200000",
        "startDelayTime": "10000",
        "contextStore": "store",
        "results": [
            {
                "p": "",
                "pt": "msgTopic",
                "v": "",
                "vt": "topic"
            },
            {
                "p": "",
                "pt": "msgPayload",
                "v": "",
                "vt": "level"
            },
            {
                "p": "slat",
                "pt": "msg",
                "v": "",
                "vt": "slat"
            },
            {
                "p": "blindCtrl",
                "pt": "msg",
                "v": "",
                "vt": "ctrlObj"
            }
        ],
        "blindIncrement": "0.05",
        "blindOpenPos": "1",
        "blindClosedPos": 0,
        "blindPosDefault": "open (max)",
        "blindPosDefaultType": "levelFixed",
        "slatPosDefault": "",
        "slatPosDefaultType": "none",
        "overwriteExpire": "",
        "rules": [],
        "sunControlMode": 16,
        "sunFloorLengthType": "num",
        "sunFloorLength": "",
        "sunMinDelta": "",
        "blindPosMin": "25%",
        "blindPosMinType": "levelFixed",
        "blindPosMax": "open (max)",
        "blindPosMaxType": "levelFixed",
        "blindOpenPosOffset": "",
        "blindClosedPosOffset": "",
        "sunSlat": "",
        "sunSlatType": "none",
        "smoothTime": "",
        "sunTopic": "",
        "windowTopType": "num",
        "windowTop": "",
        "windowBottomType": "num",
        "windowBottom": "",
        "windowAzimuthStartType": "numAzimuth",
        "windowAzimuthStart": "0",
        "windowAzimuthEndType": "numAzimuth",
        "windowAzimuthEnd": "359.9",
        "oversteers": [
            {
                "mode": 16,
                "valueType": "flow",
                "value": "#:(store)::shadow",
                "operator": "equal",
                "operatorText": "=",
                "thresholdType": "str",
                "threshold": "W",
                "onlySunInWindow": false,
                "blindPos": {
                    "type": "levelFixed",
                    "value": "open (max)"
                },
                "slatPos": {
                    "type": "none",
                    "value": ""
                }
            }
        ],
        "oversteerTopic": "",
        "x": 620,
        "y": 320,
        "wires": [
            [],
            []
        ]
    }
]
```

**Comment by nikipore** [comment]
Yes that did the job. Test flow works now. Thanks!

**Comment by nikipore** [comment]
There still seems to be a bug. Look at this flow:
```json
[{"id":"16787abdb20404ee","type":"tab","label":"Flow 1","disabled":false,"info":"","env":[]},{"id":"dc6f132e12264e56","type":"inject","z":"16787abdb20404ee","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"W","payloadType":"str","x":210,"y":100,"wires":[["5c9d036eb47e31f2"]]},{"id":"2b08a4d7ba5db4af","type":"inject","z":"16787abdb20404ee","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"str","x":210,"y":140,"wires":[["5c9d036eb47e31f2"]]},{"id":"5c9d036eb47e31f2","type":"change","z":"16787abdb20404ee","name":"","rules":[{"t":"set","p":"#:(store)::shadow","pt":"flow","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":410,"y":120,"wires":[[]]},{"id":"c0fdf4fca6318b09","type":"blind-control","z":"16787abdb20404ee","name":"Case 1","topic":"","addIdType":"none","addId":"","positionConfig":"a962ddc.fbff22","autoTrigger":false,"autoTriggerTime":"1200000","startDelayTime":"10000","contextStore":"store","results":[{"p":"","pt":"msgTopic","v":"","vt":"topic"},{"p":"","pt":"msgPayload","v":"","vt":"level"},{"p":"slat","pt":"msg","v":"","vt":"slat"},{"p":"blindCtrl","pt":"msg","v":"","vt":"ctrlObj"}],"blindIncrement":"0.05","blindOpenPos":"1","blindClosedPos":0,"blindPosDefault":"open (max)","blindPosDefaultType":"levelFixed","slatPosDefault":"","slatPosDefaultType":"none","overwriteExpire":"","rules":[],"sunControlMode":16,"sunFloorLengthType":"num","sunFloorLength":"","sunMinDelta":"","blindPosMin":"25%","blindPosMinType":"levelFixed","blindPosMax":"open (max)","blindPosMaxType":"levelFixed","blindOpenPosOffset":"","blindClosedPosOffset":"","sunSlat":"","sunSlatType":"none","smoothTime":"","sunTopic":"","windowTopType":"num","windowTop":"","windowBottomType":"num","windowBottom":"","windowAzimuthStartType":"numAzimuth","windowAzimuthStart":"0","windowAzimuthEndType":"numAzimuth","windowAzimuthEnd":"359.9","oversteers":[{"mode":0,"valueType":"flow","value":"#:(store)::shadow","operator":"equal","operatorText":"=","thresholdType":"str","threshold":"W","onlySunInWindow":false,"blindPos":{"type":"levelFixed","value":"open (max)"},"slatPos":{"type":"none","value":""}}],"oversteerTopic":"","x":840,"y":220,"wires":[[],[]]},{"id":"b66f3a99cf03f739","type":"inject","z":"16787abdb20404ee","name":"","props":[{"p":"parts","v":"43200000","vt":"str"}],"repeat":"1","crontab":"","once":true,"onceDelay":0.1,"topic":"","x":370,"y":280,"wires":[["c67190998dee0b72"]]},{"id":"37a58b5e5c46f4a7","type":"blind-control","z":"16787abdb20404ee","name":"Case 2","topic":"","addIdType":"none","addId":"","positionConfig":"a962ddc.fbff22","autoTrigger":false,"autoTriggerTime":"1200000","startDelayTime":"10000","contextStore":"store","results":[{"p":"","pt":"msgTopic","v":"","vt":"topic"},{"p":"","pt":"msgPayload","v":"","vt":"level"},{"p":"slat","pt":"msg","v":"","vt":"slat"},{"p":"blindCtrl","pt":"msg","v":"","vt":"ctrlObj"}],"blindIncrement":"0.05","blindOpenPos":"1","blindClosedPos":0,"blindPosDefault":"open (max)","blindPosDefaultType":"levelFixed","slatPosDefault":"","slatPosDefaultType":"none","overwriteExpire":"","rules":[],"sunControlMode":"16","sunFloorLengthType":"num","sunFloorLength":"","sunMinDelta":"","blindPosMin":"25%","blindPosMinType":"levelFixed","blindPosMax":"open (max)","blindPosMaxType":"levelFixed","blindOpenPosOffset":"","blindClosedPosOffset":"","sunSlat":"","sunSlatType":"none","smoothTime":"","sunTopic":"","windowTopType":"num","windowTop":"","windowBottomType":"num","windowBottom":"","windowAzimuthStartType":"numAzimuth","windowAzimuthStart":"0","windowAzimuthEndType":"numAzimuth","windowAzimuthEnd":"359.9","oversteers":[{"mode":16,"valueType":"flow","value":"#:(store)::shadow","operator":"equal","operatorText":"=","thresholdType":"str","threshold":"W","onlySunInWindow":false,"blindPos":{"type":"levelFixed","value":"open (max)"},"slatPos":{"type":"none","value":""}}],"oversteerTopic":"","x":840,"y":320,"wires":[[],[]]},{"id":"7b3b7455e63fc3ae","type":"inject","z":"16787abdb20404ee","name":"mode 0","props":[{"p":"mode","v":"0","vt":"num"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":370,"y":340,"wires":[["c67190998dee0b72"]]},{"id":"702be48c3566e227","type":"inject","z":"16787abdb20404ee","name":"mode 2","props":[{"p":"mode","v":"2","vt":"num"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":370,"y":380,"wires":[["c67190998dee0b72"]]},{"id":"70f6a15ab66b6b5c","type":"link in","z":"16787abdb20404ee","name":"","links":["c67190998dee0b72"],"x":665,"y":280,"wires":[["c0fdf4fca6318b09","37a58b5e5c46f4a7"]]},{"id":"c67190998dee0b72","type":"link out","z":"16787abdb20404ee","name":"","mode":"link","links":["70f6a15ab66b6b5c"],"x":565,"y":280,"wires":[]}]
```
It is very similar to the last flow – but it has the option to override `mode` with a message. Now:
1. Let the flow start up and set the `shadow` variable. Everything works fine in the fixed version.
2. Inject a `{mode: 2}` message, which shouldn't change anything as the nodes are already in mode 2. Now, it doesn't work any more, just as before the fix.

**Comment by Hypnos3** [comment]
This has changed in a previous version and the documentation wrong.

2 is no longer a valid value. The values for the mode are:
    const cWinterMode = 1;
    const cMinimizeMode = 3;
    const cSummerMode = 16;

I will ad a backward compatibility check for value 2 and an error for invalid values.

**Comment by nikipore** [comment]
Adapted my flow to these parameters, and it works now.
